"""Exhaustive decision table: every consent × channel-preference combination (120 rows), run through the bot.

Writes plans/decision-table-channel.md for SME review, and checks each row against the written policy.
Exits 1 if any row breaks the policy.

  uv run python scripts/decision_table.py          # build the table, check every row
  uv run python scripts/decision_table.py --sme    # also print only the rows an SME must decide
"""
import asyncio
import copy
import json
import sys
from collections import Counter
from itertools import permutations, product
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from outreach.pipeline import process, sent_message  # noqa: E402

CHANNELS = ["sms", "email", "voice"]
SUPPORTED = {"sms", "email", "voice"}


def policy(consent: dict, prefs: tuple) -> str | None:
    """The written policy, stated independently of the bot's code: first preferred, supported, consented channel."""
    return next((c for c in prefs if c in SUPPORTED and consent[c]), None)


def main() -> int:
    base = json.loads((ROOT / "plans" / "sample.jsonl").read_text().splitlines()[0])
    base.pop("expected")
    prefs_all = [p for k in (1, 2, 3) for p in permutations(CHANNELS, k)]            # 15 orderings
    consents = [dict(zip(CHANNELS, v)) for v in product([True, False], repeat=3)]  # 8 consent patterns
    rows, bad = [], []

    async def run_all():
        tasks = []
        for consent, prefs in product(consents, prefs_all):
            rec = copy.deepcopy(base)
            rec["task_id"] = f"dt_{'-'.join(prefs)}_{''.join('Y' if consent[c] else 'n' for c in CHANNELS)}_day0"
            rec["consent"] = {f"{c}_opt_in": consent[c] for c in CHANNELS}
            rec["channel_preferences"] = list(prefs)
            tasks.append((consent, prefs, process(rec)))
        return [(c, p, await t) for c, p, t in tasks]

    for consent, prefs, out in asyncio.run(run_all()):
        got = (sent_message(out) or {}).get("channel")
        want = policy(consent, prefs)
        reason = out["meta"].get("no_send_reason", "")
        note = "SME: consent without preference" if got is None and "not in preferences" in reason else ""
        rows.append((prefs, consent, got, reason, want, note))
        if got != want or (got and not consent.get(got)):
            bad.append((prefs, consent, got, want))

    counts = Counter(r[2] or "no send" for r in rows)
    reasons = Counter(r[3].split(" (")[0] for r in rows if not r[2])
    review = [r for r in rows if r[5]]
    lines = [
        "# Decision Table: Consent × Channel Preference",
        "",
        "> Generated by `uv run python scripts/decision_table.py`. Every combination of the three consent flags",
        "> (8) and every ordering of preferred channels (15), run through the bot: **120 rows**. Each row is also",
        "> checked against the written policy: *send on the first preferred channel that is supported (SMS, email,",
        "> voice) and consented; otherwise don't send.* Voice sends an automated call script (shape inferred).",
        "",
        f"**Result:** {len(rows) - len(bad)}/{len(rows)} rows match the policy. "
        + ", ".join(f"{k}: {v}" for k, v in counts.most_common()) + ".",
        "",
        "**Why no send (" + str(counts["no send"]) + " rows):** " + ", ".join(f"{k}: {v}" for k, v in reasons.most_common()) + ".",
        "",
        "**For SME review:**",
        "",
        f"- **{len(review)} rows** have a consented channel that isn't in the person's preference list, so the bot "
        "doesn't send. Is that right, or should consent alone be enough? (Current choice: respect the preference list.)",
        "",
        "| # | Preferences (in order) | SMS | Email | Voice | Bot sends via | Reason if not sent | Policy | Review |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for i, (prefs, consent, got, reason, want, note) in enumerate(rows, 1):
        yn = lambda c: "✔" if consent[c] else "·"  # noqa: E731
        lines.append(f"| {i} | {' → '.join(prefs)} | {yn('sms')} | {yn('email')} | {yn('voice')} | "
                     f"{('**' + got + '**') if got else 'no send'} | {reason} | {'✅' if (got == want) else '❌'} | {note} |")
    (ROOT / "plans" / "decision-table-channel.md").write_text("\n".join(lines) + "\n")

    print(f"{len(rows)} combinations: {len(rows) - len(bad)} match the policy, {len(bad)} do not.")
    print("  " + ", ".join(f"{k}: {v}" for k, v in counts.most_common()))
    print(f"  {len(review)} row(s) flagged for SME review (consented channel not in preferences)")
    print("  wrote plans/decision-table-channel.md")
    if "--sme" in sys.argv:
        print("\nROWS FOR SME REVIEW: consented, but the channel isn't in the preference list, so the bot doesn't send")
        print(f"  {'#':>3}  {'preferences':<22} {'SMS':^5}{'Email':^7}{'Voice':^7} reason")
        for i, (prefs, consent, got, reason, want, note) in enumerate(rows, 1):
            if note:
                yn = lambda c: "yes" if consent[c] else " - "  # noqa: E731
                print(f"  {i:>3}  {' > '.join(prefs):<22} {yn('sms'):^5}{yn('email'):^7}{yn('voice'):^7} {reason}")
        print("  Question for the SME: should consent alone be enough to use that channel?")
    for prefs, consent, got, want in bad[:10]:
        print(f"  ❌ prefs {prefs} consent {consent}: bot {got}, policy {want}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
